package com.example.easyfill_project.chatbot.model

enum class BotIntent {
    EXPLAIN_SCREEN,
    EXPLAIN_FIELD,

    USER_CONFUSED,
    USER_STRESSED,

    READ_ALOUD,
    STOP_READING,

    ENABLE_AUTO_READ,
    DISABLE_AUTO_READ,

    OPEN_PERSONAL_SETTINGS,
    OPEN_CONTRAST_SETTINGS,
    OPEN_FONT_SIZE_SETTINGS,
    OPEN_BACKGROUND_SOUNDS,

    PLAY_NATURE_SOUND,
    PLAY_CALM_MUSIC,
    PLAY_INSTRUMENT_SOUND,
    STOP_BACKGROUND_MUSIC,

    SET_CONTRAST_DEFAULT,
    SET_CONTRAST_HIGH,
    SET_CONTRAST_LOW,

    SET_FONT_SMALL,
    SET_FONT_NORMAL,
    SET_FONT_LARGE,

    VOICE_INPUT_HELP,

    GENERAL_HELP
}